# Generated by Django 3.2.4 on 2021-06-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_comment_postlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='likepost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='backend_app.post'),
            preserve_default=False,
        ),
    ]
