# Generated by Django 3.2.4 on 2021-06-12 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_app', '0004_auto_20210612_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='likeusers',
        ),
        migrations.AddField(
            model_name='postlikes',
            name='likeusers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
