# Generated by Django 3.2.4 on 2021-06-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
